#pragma once

#define LIBIMAGE_PNG
#define LIBIMAGE_BMP

//#define LIBIMAGE_NO_COLOR
//#define LIBIMAGE_NO_GRAYSCALE
//#define LIBIMAGE_NO_WRITE
//#define LIBIMAGE_NO_RESIZE
//#define LIBIMAGE_NO_PARALLEL
//#define LIBIMAGE_NO_FILESYSTEM

//#define LIBIMAGE_NO_CPP17
//#define LIBIMAGE_NO_SIMD



#define INTEL_CPU
//#define RPI_3B_PLUS
//#define JETSON_NANO


#ifndef LIBIMAGE_NO_SIMD

#ifdef INTEL_CPU

#define SIMD_INTEL_128
//#define SIMD_INTEL_256

#endif // INTEL_CPU

#ifdef RPI_3B_PLUS

#define SIMD_ARM_NEON

#endif

#ifdef JETSON_NANO

#define SIMD_ARM_NEON
#define LIBIMAGE_NO_CPP17

#endif // JETSON_NANO

#endif // !LIBIMAGE_NO_SIMD


#ifdef LIBIMAGE_NO_CPP17

#define LIBIMAGE_NO_PARALLEL
#define LIBIMAGE_NO_FILESYSTEM

#endif // LIBIMAGE_NO_CPP17
